#include "common.h"

#define FULLSCREEN_GRAPHICS_INDEX TEMP_VAR_A
#define FULLSCREEN_GRAPHICS_TILE_COUNT TEMP_VAR_A

#define FULLSCREEN_GRAPHICS_TITLESCREEN_INDEX 0u
#define FULLSCREEN_GRAPHICS_LOOT_SCENE_INSTRUCTIONS_INDEX 1u

void loadFullScreenGraphics();