#include "common.h"

#define UI_GRAPHICS_INDEX TEMP_VAR_A
#define UI_GRAPHICS_VRAM_START TEMP_VAR_B
#define UI_GRAPHICS_TILE_COUNT TEMP_VAR_A

#define UI_GRAPHICS_WINDOW_BORDERS_INDEX 0u
#define UI_GRAPHICS_SMALL_ARROWS_INDEX 1u
#define UI_GRAPHICS_GAUGE_GRAPHICS_INDEX 2u
#define UI_GRAPHICS_STAT_ICONS_INDEX 3u
#define UI_GRAPHICS_EQUIP_SLOTS_INDEX 4u
#define UI_GRAPHICS_FRIEND_FOE_INDEX 5u
#define UI_GRAPHICS_BATTLE_CURSOR_INDEX 6u
#define UI_GRAPHICS_TOGGLE_INDEX 7u

void loadUIGraphics();