/*

 ICON_SMALL_ARROWS.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : 8x8-count as Constant.
  Tile size            : 8 x 8
  Tiles                : 0 to 3

  Palette colors       : None.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Icon_Small_Arrows_h_INCLUDE
#define __Icon_Small_Arrows_h_INCLUDE

/* Bank of tiles. */
#define Icon_Small_ArrowsBank 0
/* Start of tile array. */
extern const unsigned char Icon_Small_Arrows[64];
#define Icon_Small_ArrowsLen 4

#endif

/* End of ICON_SMALL_ARROWS.H */
