/*

 TITLE_SALVAGEFRONTIER_MAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : Z:\home\mreichelt\workspace\gameboy_development\BuriedMechs\res\BuriedMechsTitleScreen_v2_SalvageFrontier.gbm.tiles.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/
#ifndef __Title_SalvageFrontier_map_h_INCLUDE
#define __Title_SalvageFrontier_map_h_INCLUDE

#define Title_SalvageFrontierWidth 20
#define Title_SalvageFrontierHeight 18
#define Title_SalvageFrontierBank 0

#define Title_SalvageFrontier Title_SalvageFrontierPLN0
extern const unsigned char Title_SalvageFrontierPLN0[];

#endif

/* End of TITLE_SALVAGEFRONTIER_MAP.H */
