/*

 TITLE_SALVAGEFRONTIER_TILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 143

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/

#ifndef __Title_SalvageFrontier_tiles_h_INCLUDE
#define __Title_SalvageFrontier_tiles_h_INCLUDE

/* Bank of tiles. */
#define TitleSalvageFrontierBank 0

/* Super Gameboy palette 0 */
#define TitleSalvageFrontierSGBPal0c0 0
#define TitleSalvageFrontierSGBPal0c1 0
#define TitleSalvageFrontierSGBPal0c2 0
#define TitleSalvageFrontierSGBPal0c3 0

/* Super Gameboy palette 1 */
#define TitleSalvageFrontierSGBPal1c0 6076
#define TitleSalvageFrontierSGBPal1c1 8935
#define TitleSalvageFrontierSGBPal1c2 6596
#define TitleSalvageFrontierSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define TitleSalvageFrontierSGBPal2c0 6076
#define TitleSalvageFrontierSGBPal2c1 8935
#define TitleSalvageFrontierSGBPal2c2 6596
#define TitleSalvageFrontierSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define TitleSalvageFrontierSGBPal3c0 6076
#define TitleSalvageFrontierSGBPal3c1 8935
#define TitleSalvageFrontierSGBPal3c2 6596
#define TitleSalvageFrontierSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define TitleSalvageFrontierCGBPal0c0 26620
#define TitleSalvageFrontierCGBPal0c1 14096
#define TitleSalvageFrontierCGBPal0c2 10662
#define TitleSalvageFrontierCGBPal0c3 4192

/* Gameboy Color palette 1 */
#define TitleSalvageFrontierCGBPal1c0 6076
#define TitleSalvageFrontierCGBPal1c1 8935
#define TitleSalvageFrontierCGBPal1c2 6596
#define TitleSalvageFrontierCGBPal1c3 5344

/* Gameboy Color palette 2 */
#define TitleSalvageFrontierCGBPal2c0 6076
#define TitleSalvageFrontierCGBPal2c1 8935
#define TitleSalvageFrontierCGBPal2c2 6596
#define TitleSalvageFrontierCGBPal2c3 5344

/* Gameboy Color palette 3 */
#define TitleSalvageFrontierCGBPal3c0 6076
#define TitleSalvageFrontierCGBPal3c1 8935
#define TitleSalvageFrontierCGBPal3c2 6596
#define TitleSalvageFrontierCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define TitleSalvageFrontierCGBPal4c0 6076
#define TitleSalvageFrontierCGBPal4c1 8935
#define TitleSalvageFrontierCGBPal4c2 6596
#define TitleSalvageFrontierCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define TitleSalvageFrontierCGBPal5c0 6076
#define TitleSalvageFrontierCGBPal5c1 8935
#define TitleSalvageFrontierCGBPal5c2 6596
#define TitleSalvageFrontierCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define TitleSalvageFrontierCGBPal6c0 6076
#define TitleSalvageFrontierCGBPal6c1 8935
#define TitleSalvageFrontierCGBPal6c2 6596
#define TitleSalvageFrontierCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define TitleSalvageFrontierCGBPal7c0 6076
#define TitleSalvageFrontierCGBPal7c1 8935
#define TitleSalvageFrontierCGBPal7c2 6596
#define TitleSalvageFrontierCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char TitleSalvageFrontier[];

#endif

/* End of TITLE_SALVAGEFRONTIER_TILES.H */
