//AUTOGENERATED FILE FROM png2asset
#ifndef METASPRITE_Toggle1x2_H
#define METASPRITE_Toggle1x2_H

#include <stdint.h>
#include <gbdk/platform.h>
#include <gbdk/metasprites.h>

#define Toggle1x2_TILE_ORIGIN 0
#define Toggle1x2_TILE_W 8
#define Toggle1x2_TILE_H 8
#define Toggle1x2_WIDTH 64
#define Toggle1x2_HEIGHT 8
#define Toggle1x2_TILE_COUNT 8
#define Toggle1x2_PALETTE_COUNT 1
#define Toggle1x2_COLORS_PER_PALETTE 4
#define Toggle1x2_TOTAL_COLORS 4

BANKREF_EXTERN(Toggle1x2_bank)

extern const uint8_t Toggle1x2_tiles[128];


#endif
